version: '2'

services:
  pa-cdev:
    container_name: pa
    image: pa-cdev
    build:
      context: ./docker
      dockerfile: pa.dockerfile
    expose:
      - 1234
    volumes:
      - ./:/home/pa
    networks:
      - cdev-network

  so-cdev:
    container_name: so
    image: so-cdev
    build:
      context: ./docker
      dockerfile: so.dockerfile
    volumes:
      - ./:/home/so
    networks:
      - cdev-network

networks:
  cdev-network:
    driver: bridge
