version: '2'

services:
  pa-cdev:
    container_name: pa
    image: pa-cdev
    build:
      context: ./docker
      dockerfile: pa.dockerfile
    expose:
      - 1234
    volumes:
      - ./:/home/pa
    networks:
      - docker-dei-network

  so-cdev:
    container_name: so
    image: so-cdev
    build:
      context: ./docker
      dockerfile: so.dockerfile
    volumes:
      - ./:/home/so
    networks:
      - docker-dei-network

  ainet-webserver:
    container_name: ainet
    image: ainet-webserver
    build:
      context: ./docker
      dockerfile: ainet.dockerfile
    volumes:
      - ./docker/conf:/etc/nginx/sites-enabled
    networks:
      - docker-dei-network

networks:
  docker-dei-network:
    driver: bridge
